name: Publish to NPM
on:
  release:
    types: [published]

permissions:
  id-token: write  # Required for OIDC authentication
  contents: read   # Required for repository access

jobs:
  npm-publish:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Use Node.js
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: "20"
          cache: "npm"
          registry-url: "https://registry.npmjs.org"
      - name: Upgrade npm to latest
        run: npm install -g npm@latest
      - run: npm ci
      - name: build binary
        run: npm run build
      - name: Publish package on NPM 📦
        run: npm publish --access public
